
/******************************************************************************
 * NOTE... This design is already completed and you do NOT need to modify it.
 * If you wish, you can make modifications to the design and properties 
 * (however, if you do, you are responsible if it causes any coding issues).
 * You ARE responsible for adding the "EXPLANATION" comment below...
 * 
 * EXPLANATION: 
 * 
 * Using a designer like here in NetBeans, or a similar designer like Visual
 * Studio, the user interface design code is often separated from the code
 * logic. This also matches several Computer Science design paradigms like
 * the MVC model (which stands for Model View Controller). The idea is that
 * this module is used to build what the user "sees" and interacts with and
 * the actual logic (or the "engine") is done in a different module (or 
 * multiple modules). The ease of the designer is used to create all the UI
 * (user interface) components and change their properties (like positions, 
 * look and feel, etc) and also add action user events (like clicking a 
 * button, etc). But then the actual logic of those actions is sent to methods
 * in the controller class. 
 * 
 * NOTE... After completing this comment in your project, examining the code,  
 * and reading all the comments below, move next to the "Meme.java" class... 
 *****************************************************************************/

/** Required package class namespace */
package cs40s.interfaces;

/**
 * UIView.java - the main user interface "view" for the user to interact with
 * in the application. The program logic for this view is passed to a controller
 * class.
 *
 * @author Mr. Wachs
 * @since December, 2020
 */
public class UIView extends javax.swing.JFrame 
{
    
    private UIController controller;        // The controller for this view

    /**
     * Default constructor, creates new form MemeDatabase (written by the
     * designer for you)
     */
    public UIView() {
        initComponents();           
        // NetBeans writes this call to the "hidden" method below to set up
        // all the design components, set thier properties, and set up the
        // action listeners for the user interactive components
        
        controller = new UIController(jLabel2, jTextField3, list1, list2, this);
        // The controller is instantitated and "linked" to this "view" and 
        // all the relevant components that it "uses"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        list2 = new java.awt.List();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meme Database");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 800, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("All Memes"));
        jPanel1.setLayout(null);

        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        jPanel1.add(list2);
        list2.setBounds(10, 30, 490, 510);

        jButton5.setText("Open Meme List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 590, 240, 30);

        jButton7.setText("Search Memes");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(260, 550, 240, 30);

        jButton8.setText("Save Meme List");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(260, 590, 240, 30);

        jButton10.setText("Delete Selected Meme");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(10, 550, 240, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(300, 60, 510, 630);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter New Meme"));
        jPanel2.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Meme Image Here");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 240, 230);

        jButton1.setText("Clear Fields");
        jButton1.setActionCommand("Clear All Fields");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 550, 240, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(130, 350, 120, 30);

        jLabel5.setText("Meme Keywords:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 350, 130, 30);

        jButton2.setText("Select Meme Image from Internet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 310, 240, 30);
        jPanel2.add(list1);
        list1.setBounds(10, 430, 240, 70);

        jButton3.setText("Delete Selected Keyword");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 510, 240, 30);

        jButton4.setText("Save Meme");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 590, 240, 30);

        jButton11.setText("Enter Meme Keyword");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(10, 390, 240, 30);

        jButton12.setText("Select Meme Image from File");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(10, 270, 240, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 270, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        controller.openMemeList();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        controller.searchMemes();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        controller.saveMemeList();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        controller.deleteSelectedMeme();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.clearFields();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.selectMemeImageFromInternet();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controller.deleteSelectedKeyword();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controller.saveMeme();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        controller.enterMemeKeyword();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        controller.selectMemeImageFromFile();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        controller.clickOnMemeList();
    }//GEN-LAST:event_list2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private java.awt.List list1;
    private java.awt.List list2;
    // End of variables declaration//GEN-END:variables

}
