
/** Required package class namespace */
package cs30s;

/** Required imports */
import javax.swing.JOptionPane;

/**
 * VehicleSelect.java - using a feature of NetBeans, the graphics user 
 * interface (GUI) designer similar to the one used in Visual Studio. It 
 * allows you to use a toolbox and add tools and a properties window to change  
 * the properties of the objects. This form is for the user to select which  
 * vehicle to use in the game. Follow the document instructions to build the
 * design in the designer and name all objects before adding this code.
 *
 * @author Mr. Wachs
 * @since December 2020
 */
public class VehicleSelect extends javax.swing.JFrame 
{

    /************************************************************************** 
     * NOTE... The method below is called a "constructor" method. Classes can
     * have this special method which has NO return type (not even "void") and
     * uses the same name for the method as the name for the class (including
     * a capital letter). The word "public" is always used with constructor 
     * methods as this method is always called outside the class when an 
     * object of this class is created (or "constructed" or "instantiated").
     * If the constructor method has no parameters, then it is called a 
     * "default" constructor method.
     *************************************************************************/ 
     
    /** 
     * Default constructor method, it sets class properties, and creates a new   
     * form VehicleSelect object. This method is written by NetBeans and the 
     * designer for you.
     */
    public VehicleSelect() {
        initComponents();
        start();                    // call a method to continue starting up
    }

    /**************************************************************************
     * NOTE... The code below is written by NetBeans and can NOT be altered. 
     * NetBeans puts a comment in the code indicating this. You CAN "collapse"
     * this code before turning this project into a PDF. Also, NetBeans will
     * write a "main" method for every JFrame form, but you can delete it.
     *************************************************************************/
    
    /** 
     * This method is called from within the constructor to initialize the
     * form.
     * 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        choose1Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        choose2Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        choose3Button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Red");

        choose1Button.setText("Choose Motorcycle");
        choose1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose1ButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Fastest");

        jLabel4.setText("Small build");

        jLabel5.setText("Cannot Take Damage");

        jLabel6.setText("Green");

        choose2Button.setText("Choose Car");
        choose2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose2ButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Medium speed");

        jLabel8.setText("Medium Build");

        jLabel9.setText("Can Take 1 Collision");

        jLabel10.setText("Blue");

        choose3Button.setText("Choose Truck");
        choose3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose3ButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Slowest");

        jLabel12.setText("Big Build");

        jLabel13.setText("Can Take 3 Collisions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(choose1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choose2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choose3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameText)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(choose3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(choose1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(choose2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choose1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose1ButtonActionPerformed
        /**********************************************************************
         * NOTE... The code below is accessed by "double clicking" the various
         * buttons in the designer.
         *********************************************************************/        
        
        choose(1);                                  // call our own method
    }//GEN-LAST:event_choose1ButtonActionPerformed

    private void choose2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose2ButtonActionPerformed
        choose(2);
    }//GEN-LAST:event_choose2ButtonActionPerformed

    private void choose3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose3ButtonActionPerformed
        choose(3);
    }//GEN-LAST:event_choose3ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choose1Button;
    private javax.swing.JButton choose2Button;
    private javax.swing.JButton choose3Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables

    /**************************************************************************
     * NOTE... The code below is not written by NetBeans and can include any
     * global variables and methods (either written by us or using the 
     * "light bulb")
     *************************************************************************/
    
    /**
     * Set up some visual elements of the form (frame) when this form first 
     * starts up (appears) - like the "Form_Load" code of Visual Studio
     */
    private void start() {
        
        /**********************************************************************
         * NOTE... Before continuing, go to "File - New File..." then select
         * "Java" and "Java Class". Name it "Globals" under "Class Name:"
         * and it will add this class to the project and open it as a code
         * tab in NetBeans. Complete that code and then return here to 
         * continue...
         *********************************************************************/
        
        this.setTitle(Globals.APPLICATION_TITLE);   // Set the form title
        this.setResizable(false);                   // Form not sizable
        this.setLocationRelativeTo(null);           // Center form on screen
        this.setVisible(true);                      // Make form appear to user
    }
    
    /**
     * React to the button click of a vehicle selection, dispose of this form 
     * and move to the next form
     * 
     * @param vehicle which button clicked and therefore which vehicle chosen
     */
    private void choose(int vehicle) {
        // Get the text out of the textbox for the name and store in variable
        String driver = nameText.getText();             
        
        // Check to make sure they filled in a name in the textbox
        if (driver == null || driver.equals("")) {
            
            // display an error message
            JOptionPane.showMessageDialog(this, 
                    "Please enter a driver's name",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            
            // Leave this method early
            return;
        }
        
        // Depending on which button the user clicked (the method parameter),
        // set a global variable in the different class (that we just created)
        if      (vehicle == 1) Globals.vehicle = new Motorcycle(driver); 
        else if (vehicle == 2) Globals.vehicle = new Car(driver); 
        else if (vehicle == 3) Globals.vehicle = new Truck(driver); 
        
        // Use "this" as a refernece to "this class object" in this case this
        // JFrame we have designed, then we call a method to "dispose" of it
        // meaning it disappears and no longer uses any memory.
        this.dispose();
        
        /**********************************************************************
         * NOTE... We will now use the code below and creating another JFrame
         * form (using the same process as before) called "GameScreen". Once 
         * this code is completed, then move on to code that class.
         *********************************************************************/
        
        // Now create a new GameScreen object and make it appear on the screen
        GameScreen screen = new GameScreen();
    }

}
